### ISSUE TITLE
Running ZBuffer instead of Mex_ZBuffer

### ISSUE THREAD

**Issue by serser** [anhttran/extreme_3d_faces#1]
I am using Mac version of Matlab. So in [3DDFA Expression Model](http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/Code/3DDFA.zip), there is an alternative Matlab version of `Z_Buffer` to `Mex_ZBufferC.mexw64`. However, the parameters list are not exactly the same:

    ZBuffer(s2d, vertex, tri, texture, img_src)

where in `Mex_ZBuffer.m`, we have,

    Mex_ZBuffer(projectedVertex, tri, texture, img_src)

what is exactly `s2d` here? And how do we get it? Thanks!

**Comment by iacopomasi** [comment]
It is hard for us to reply to this: you should contact 3DDFA author asking them about this problem. Probably the interface to the function is slightly different between the Windows and Mac version.

**Comment by marvin521** [comment]
@serser   I have the same problem. How do you solve the problem?
