### ISSUE TITLE
TestBump Issue

### ISSUE THREAD

**Issue by risingsunho** [anhttran/extreme_3d_faces#11]
I think modules/TestBump is missing in your github.
when i build i can see Message below :

[ 14%] Built target CvGl
[ 85%] Built target PoseExprLib
[ 92%] Linking CXX executable ../bin/TestBump
/usr/bin/ld: cannot find -lopencv_dep_cudart
collect2: error: ld returned 1 exit status
config/CMakeFiles/TestBump.dir/build.make:127: recipe for target 'bin/TestBump' failed
make[2]: *** [bin/TestBump] Error 1
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestBump.dir/all' failed
make[1]: *** [config/CMakeFiles/TestBump.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Could you tell me What is the problem?

**Comment by anhttran** [comment]
In CMakeLists.txt, you can set CUDA_USE_STATIC_CUDA_RUNTIME as OFF:
https://github.com/opencv/opencv/issues/6542

I will update my code soon.

**Comment by anhttran** [comment]
Updated: https://github.com/anhttran/extreme_3d_faces/blob/master/CMakeLists.txt#L7

**Comment by heruiyuan** [comment]
I have the same question but add set CUDA static runtime doesn't work!!

**Comment by lhyfst** [comment]
I also cannot find the TestBump

```
root@0b9ad418b7dd:/app/demoCode# ./testPaperResults.sh
./testPaperResults.sh: line 4: ./TestBump: No such file or directory
```
