### ISSUE TITLE
Removing facial fine details (wrinkles, etc)

### ISSUE THREAD

**Issue by tsly123** [anhttran/extreme_3d_faces#18]
Hi,
Thank you for sharing your work.
Is there any way to remove the facial fine details like wrinkles from 3D reconstructed face, and keep the facial expression in the same time?
By the way, I've read the paper. Although it's seem to me that fine details and expression don't related much to each other, just want to make sure.

Thank you,
tlsy

**Comment by anhttran** [comment]
Sorry for my late response. You can output the foundation 3D model (shape + expression) by changing this config: https://github.com/anhttran/extreme_3d_faces/blob/master/main.cpp#L139

**Comment by tsly123** [comment]
Thank you for your answer.

Although I havent tried to produce the foundation shape yet, but your original code worked incredibly. I also have 2 more questions, hope you could help me with it.

1. I tried your original code, and it works. In the process, it display the "cuda opengl windows". Do you know how to disable that display windows? I want to implement the code in the server which cant display anything.
2. I have also read the ExpNet paper which mentioned in your paper. I would like to know how to combine your code to ExpNet code. If you cant give me full answer, some hints would be much appreciated.

Thank you.
tsly

**Comment by lhyfst** [comment]
Dear author, for unknown reasons, my 3d reconstructed faces don't have fine details. Could you please kindly tell me how to add the fine details to the 3d reconstructed faces? @anhttran

**Comment by lhyfst** [comment]
I opened a new issue for this problem.
https://github.com/anhttran/extreme_3d_faces/issues/51
