### ISSUE TITLE
Build failed at 92% with No rule to make target error

### ISSUE THREAD

**Issue by vivekaditya** [anhttran/extreme_3d_faces#2]
```
Scanning dependencies of target TestBump
[ 92%] Building CXX object config/CMakeFiles/TestBump.dir/__/main.cpp.o
make[2]: *** No rule to make target '/home/ubuntu/Downloads/opencv-2.4.9/release/lib/libopencv_ts.a', needed by 'bin/TestBump'.  Stop.
CMakeFiles/Makefile2:196: recipe for target 'config/CMakeFiles/TestBump.dir/all' failed
make[1]: *** [config/CMakeFiles/TestBump.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Tried with both the branches master as well as linux. The complete setup was followed. Let me know if something is missing

**Comment by iacopomasi** [comment]
Hi @vivekaditya ,
I was able to compile it properly under a CentOS Linux distribution. 
It looks like the error is related to your OpenCV installation. 

For example, have you tried to see if `/home/ubuntu/Downloads/opencv-2.4.9/release/lib/libopencv_ts.a` does exist?

PS
Note that we are still working on the code release.

**Comment by anhttran** [comment]
It should link to the shared objects (libopencv*.so) instead of the static ones.

**Comment by hereitag** [comment]
Solved by redirecting Dlib in the makelist.

**Comment by aleXiehta** [comment]
Hi, I met this issue, too.
I've checked `libopencv_ts.a`, but don't understand how to link to the shared objects.

Many thanks!
