### ISSUE TITLE
How to blend the bump map

### ISSUE THREAD

**Issue by LogicHolmes** [anhttran/extreme_3d_faces#25]
Hello, Sir,

I would like to use the network to regression bump map! But i don`t know how to blend the bump map, do you have any idea?

I look forward you can help me! Thanks you so much!

**Comment by iacopomasi** [comment]
@LogicHolmes the bump map encodes 3D information. It actually encodes the deviation from the 3D information. The code will do the "blending" for you but not in the 2D image space but in 3D. It will add back the "delta" to the base foundation model. Just check the cpp code.

I hope this helps,
cheers

**Comment by LogicHolmes** [comment]
Thanks for you help me. But i could not find which the cpp code is blend the bump map. Could you help me point where the code is. Thank you!

**Comment by ZHJNCUT** [comment]
> 谢谢你帮助我。但我找不到哪个 cpp 代码是混合凹凸贴图的。你能帮我指出代码在哪里吗？谢谢你！

May I ask if you have found the relevant cpp code? I want to check and learn it, thank you

**Comment by ZHJNCUT** [comment]
> @LogicHolmes凹凸贴图对 3D 信息进行编码。它实际上对 3D 信息的偏差进行编码。该代码将为您进行“混合”，但不是在 2D 图像空间中，而是在 3D 中。它将把“增量”添加回基础模型中。只需检查cpp代码即可。
> 
> 我希望这有帮助， 干杯

May I ask if you have found the relevant cpp code? I want to check and learn it, thank you
