### ISSUE TITLE
Dockerfile need update due to pytorch version not compatible with torchvision

### ISSUE THREAD

**Issue by dzk9528** [anhttran/extreme_3d_faces#27]
According to https://github.com/quark0/darts/issues/9
In Dockerfile
torchvision version should be less than 0.2.1
RUN pip install opencv-python torchvision==0.2.1 scikit-image cvbase pandas mmdnn dlib

Just want to bring it up in case anyone use the Docker. (Feel free to close issuer if the author already change the Dockerfile)

**Comment by anhttran** [comment]
Thanks a lot for your suggestion. I have updated my Dockerfile.
