### ISSUE TITLE
TypeError: data type "floattrimBaselFace.py64" not understood

### ISSUE THREAD

**Issue by lvzhihan** [anhttran/extreme_3d_faces#29]
When I run python trimBaselFace.py of /3DMM_model directory, it come out TypeError: data type "floattrimBaselFace.py64" not understood, who can tell me how to solve it.

(extreme3D) event@event2:~/Documents/extreme_3d_faces-master/3DMM_model$ python trimBaselFace.py
Traceback (most recent call last):
  File "trimBaselFace.py", line 104, in <module>
    shapeEV = convert(shapeEV)
  File "trimBaselFace.py", line 27, in convert
    new = data.reshape(data.shape[0],1).astype('floattrimBaselFace.py64')
TypeError: data type "floattrimBaselFace.py64" not understood

**Comment by anhttran** [comment]
Maybe your computer or your Python is 32bit. You can change 'float64' to 'float':
[https://github.com/anhttran/extreme_3d_faces/blob/master/3DMM_model/trimBaselFace.py#L27](url)
