### ISSUE TITLE
BaselFaceEstimator.cpp:224:2: error: ‘Rodrigues’ is not a member of ‘cv’

### ISSUE THREAD

**Issue by jtou100** [anhttran/extreme_3d_faces#3]
I complie this code and happend this question.
I didn't how to reslove it,Could you help me?

**Comment by jtou100** [comment]
I have fix it, I used the opencv 3.3 and I changed the version to 2.4.10, everything is ok

**Comment by FelipeCrispim** [comment]
Hello,

Could you explain me better how you could fix it? I'm using opencv 3.4 but I'm still getting the same error.

Thank you.
