### ISSUE TITLE
fatal error: cv.h: No such file or directory #include "cv.h"

### ISSUE THREAD

**Issue by theimgclist** [anhttran/extreme_3d_faces#30]
I was trying to execute the steps mentioned and I am stuck due to the below error. It looks like opencv issue but I am not able to figure out the fix. Appreciate any help. Thanks!

`In file included from Projects/ExtremeFaces/extreme_3d_faces/modules/CvGl/FBRender.cpp:2:0:
Projects/ExtremeFaces/extreme_3d_faces/modules/CvGl/FBRender.h:21:10: fatal error: cv.h: No such file or directory
 #include "cv.h"
          ^~~~~~
compilation terminated.
modules/CvGl/CMakeFiles/CvGl.dir/build.make:62: recipe for target 'modules/CvGl/CMakeFiles/CvGl.dir/FBRender.cpp.o' failed
make[2]: *** [modules/CvGl/CMakeFiles/CvGl.dir/FBRender.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'modules/CvGl/CMakeFiles/CvGl.dir/all' failed
make[1]: *** [modules/CvGl/CMakeFiles/CvGl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by anhttran** [comment]
My code uses OpenCV2. You can try Docker option or convert my code to OpenCV3.
Here is how to convert my previous project code to OpenCV3. It should be similar in this project:
[https://github.com/anhttran/3dmm_cnn/pull/45/commits/d3c8298f12382f48cf2ffd689275e7ca4edb713f](url)

**Comment by lastapple** [comment]
emmm, the link is invalid......

**Comment by Water-Silver** [comment]
How was this fixed? The link is no longer available. Thanks.

**Comment by ZHJNCUT** [comment]
> 这是如何解决的？该链接不再可用。谢谢。

Have you solved the problem?
