### ISSUE TITLE
GPU RAM size required to run bump maps.

### ISSUE THREAD

**Issue by HaiyongJiang** [anhttran/extreme_3d_faces#35]
Dear authors, thank you for your great work. I test the code on my server with the provided dockfile. However, the program complains "out of memory" when regressing bump maps. Can you kindly inform me of the memory size of your testing GPU? Thank you.

**Comment by anhttran** [comment]
I do not know why this issue appeared recently. You can fix it by adding "
volatile=True" as in my update below:
https://github.com/anhttran/extreme_3d_faces/blob/master/demoCode/bumpMapRegressor.py#L320

**Comment by HaiyongJiang** [comment]
Now it works well. Thank you.
