### ISSUE TITLE
There was an error acquiring 3DDFA Expression Model

### ISSUE THREAD

**Issue by wuxiaolianggit** [anhttran/extreme_3d_faces#41]
There was an error acquiring 3DDFA Expression Model，Can you provide Expression Model to Google cloud disk，thanks very much.

**Comment by wuxiaolianggit** [comment]
There was an error acquiring 3DDFA Expression Model，Can you provide Expression Model to Google cloud disk，thanks very much. @YuvalNirkin

**Comment by anhttran** [comment]
The Expression Model is still downloadable. Check `http://www.cbsr.ia.ac.cn/users/xiangyuzhu/projects/3DDFA/Code/3DDFA.zip` and you can find it at `/3DDFA_Release/Matlab/Model_Expression.mat`

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply，Testing other pictures will lead to the following situation. How to solve it？
![image](https://user-images.githubusercontent.com/34123600/81406662-91648180-916c-11ea-8e8e-2aeea7e305a0.png)

![image](https://user-images.githubusercontent.com/34123600/81406700-a93c0580-916c-11ea-838b-5191b69aaebe.png)

**Comment by wuxiaolianggit** [comment]
Thank you very much for your reply. When testing other pictures, the above results will appear. How to solve them?
image@ @anhttran

**Comment by wuxiaolianggit** [comment]
When testing other pictures, the above results will appear. How to solve them? @ @YuvalNirkin

**Comment by wuxiaolianggit** [comment]
![image](https://user-images.githubusercontent.com/34123600/81778180-e9143b80-9524-11ea-95b4-45acdc3997d9.png)

When testing other pictures, the above results will appear. How to solve them? @iacopomasi

**Comment by anhttran** [comment]
I looks strange. Did you generate `BaselFaceModel_mod.mat` and `BaselFaceModel_mod.h5` with `trimBaselFace.py`?

Can you try this code to make sure your mat file (and the h5 file respectively) is correct?

```
import utils
import scipy.io
import numpy as np

BFM_path = '../3DMM_model/BaselFaceModel_mod.mat'
model = scipy.io.loadmat(BFM_path,squeeze_me=True,struct_as_record=False)
model = model["BFM"]
faces = model.faces-1

S,T = utils.projectBackBFM(model,np.zeros((198)))
gamma = np.zeros((29))
gamma[0] = -3
E = utils.projectBackExp(model,gamma)
utils.write_ply('test.ply', S+E, T, faces)
```

**Comment by wuxiaolianggit** [comment]
First of all, thank you very much for your reply，I did use trimBaselFace.py to generate BaselFaceModel_mod.mat and BaselFaceModel_mod.h5，I try to use the above methods to solve this problem. @anhttran
