### ISSUE TITLE
missing files in output

### ISSUE THREAD

**Issue by baileyztsang** [anhttran/extreme_3d_faces#44]
Thanks for sharing your code! I followed the instructions to run with docker and managed to run the democode with no errors but there are no ply files showing in any of the ouput folders (3d, bump, shape). My terminal shows that the images were all processed correctly and I can see the .pts and image with landmarks photos saved in imgs folder where the original images are located. Any idea what happened to the ply files? Thanks!

**Comment by ZHJNCUT** [comment]
> 感谢您分享您的代码！我按照说明使用 docker 运行并成功运行演示代码，没有错误，但任何输出文件夹（3d、凹凸、形状）中都没有显示层文件。我的终端显示图像均已正确处理，我可以看到 .pts 和带有地标照片的图像保存在原始图像所在的 imgs 文件夹中。知道层文件发生了什么吗？谢谢！

Have you solved it yet？
