### ISSUE TITLE
AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats' occured ?? When I installed torch==1.40 and torchvision==0.5.0

### ISSUE THREAD

**Issue by heruiyuan** [anhttran/extreme_3d_faces#46]
What its pytorch version? I have some issues about the pytorch version of AttributeError: 'BatchNorm2d' object has no attribute 'track_running_stats'

**Comment by anhttran** [comment]
It uses Pytorch 0.3. You can check the Dockerfile to see the required libraries.

**Comment by heruiyuan** [comment]
Wa~ I just open and see it！Thank You！
