### ISSUE TITLE
Getting following error during build make process.

### ISSUE THREAD

**Issue by likwifi** [anhttran/extreme_3d_faces#6]
/home/minas/extreme_3d_faces-master/modules/PoseExpr/src/BaselFaceEstimator.cpp:224:6: error: ‘Rodrigues’ is not a member of ‘cv’
  cv::Rodrigues(rMatP, rVec);
      ^~~~~~~~~

**Comment by YuvalNirkin** [comment]
Use OpenCV 2.4.
