### ISSUE TITLE
minor bug maybe

### ISSUE THREAD

**Issue by fwbx529** [anhttran/extreme_3d_faces#9]
In modules/PoseExpr/src/FaceServices2.cpp, line 390
I think it should be as followed (init with 0)

cv::Mat out(2*M+EM+RENDER_PARAMS_COUNT,1,CV_32F,cv::Scalar(0));

as when I check the different output of the same data, this function computeGradient sometimes gives me a mat containing some NANs
 
![image](https://user-images.githubusercontent.com/16728292/40576043-a00b83c2-6122-11e8-8ec5-9d4233c3298c.png)

**Comment by anhttran** [comment]
Depend on the optimizing stage, I do not set and use some parameters. Hence, it is fine if their values are NANs. Regardless, many thanks for your suggestion.
